/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as DirectoryCrawlerIndexRouteImport } from './routes/directory-crawler/index'
import { Route as CrawlJobsIndexRouteImport } from './routes/crawl-jobs/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryCrawlerIndexRoute = DirectoryCrawlerIndexRouteImport.update({
  id: '/directory-crawler/',
  path: '/directory-crawler/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlJobsIndexRoute = CrawlJobsIndexRouteImport.update({
  id: '/crawl-jobs/',
  path: '/crawl-jobs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crawl-jobs/': typeof CrawlJobsIndexRoute
  '/directory-crawler/': typeof DirectoryCrawlerIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crawl-jobs': typeof CrawlJobsIndexRoute
  '/directory-crawler': typeof DirectoryCrawlerIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crawl-jobs/': typeof CrawlJobsIndexRoute
  '/directory-crawler/': typeof DirectoryCrawlerIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crawl-jobs/' | '/directory-crawler/' | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crawl-jobs' | '/directory-crawler' | '/resources'
  id: '__root__' | '/' | '/crawl-jobs/' | '/directory-crawler/' | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrawlJobsIndexRoute: typeof CrawlJobsIndexRoute
  DirectoryCrawlerIndexRoute: typeof DirectoryCrawlerIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory-crawler/': {
      id: '/directory-crawler/'
      path: '/directory-crawler'
      fullPath: '/directory-crawler/'
      preLoaderRoute: typeof DirectoryCrawlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawl-jobs/': {
      id: '/crawl-jobs/'
      path: '/crawl-jobs'
      fullPath: '/crawl-jobs/'
      preLoaderRoute: typeof CrawlJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrawlJobsIndexRoute: CrawlJobsIndexRoute,
  DirectoryCrawlerIndexRoute: DirectoryCrawlerIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
